/**
 * HeatmapLayer — pre-computed grid-based heatmap for Leaflet.
 *
 * Fetches a pre-computed score grid from /heatmap/{dimension}.json
 * (generated by scripts/generate_heatmap.py) and renders it using
 * Leaflet's L.GridLayer tile system with bilinear interpolation
 * for smooth color transitions between grid cells.
 *
 * Each grid JSON contains scores at ~400m resolution covering all
 * of NYC. The data is real (computed from actual crime, noise, transit,
 * park, greenery, and convenience datasets) — not interpolated from
 * listing locations.
 *
 * Color scale: green (≥75) → yellow (≥50) → orange (≥25) → red (<25).
 */

"use client";

import { useEffect, useRef, useState } from "react";
import { useMap } from "react-leaflet";
import type { ScoreDimension } from "@/lib/types";
import L from "leaflet";

interface HeatmapLayerProps {
  dimension: ScoreDimension;
}

// ── Grid data shape (matches JSON from generate_heatmap.py) ─────

interface GridData {
  bounds: { minLat: number; maxLat: number; minLng: number; maxLng: number };
  rows: number;
  cols: number;
  latStep: number;
  lngStep: number;
  scores: (number | null)[][];
}

// ── Map overlay key → JSON filename ─────────────────────────────

const GRID_FILE: Partial<Record<ScoreDimension, string>> = {
  parks: "green_space", // blended parks + greenery
};

function gridFileFor(dimension: ScoreDimension): string {
  return GRID_FILE[dimension] ?? dimension;
}

// ── Color helpers ───────────────────────────────────────────────

type RGB = [number, number, number];

function lerpColor(a: RGB, b: RGB, t: number): RGB {
  return [
    Math.round(a[0] + (b[0] - a[0]) * t),
    Math.round(a[1] + (b[1] - a[1]) * t),
    Math.round(a[2] + (b[2] - a[2]) * t),
  ];
}

const RED: RGB = [239, 68, 68];
const ORANGE: RGB = [249, 115, 22];
const YELLOW: RGB = [234, 179, 8];
const GREEN: RGB = [34, 197, 94];

function scoreToRgb(score: number): RGB {
  const s = Math.max(0, Math.min(100, score));
  if (s >= 75) return lerpColor(YELLOW, GREEN, (s - 75) / 25);
  if (s >= 50) return lerpColor(ORANGE, YELLOW, (s - 50) / 25);
  if (s >= 25) return lerpColor(RED, ORANGE, (s - 25) / 25);
  return RED;
}

// ── Tile rendering constants ────────────────────────────────────

const TILE_SIZE = 256;
const PIXEL_STEP = 4; // Render every Nth pixel then upscale for perf
const OPACITY = 0.30;

// ── Bilinear interpolation on the grid ──────────────────────────

function sampleGrid(grid: GridData, lat: number, lng: number): number | null {
  const { bounds, rows, cols, scores } = grid;

  // Convert lat/lng to continuous grid coordinates
  // Row 0 = maxLat (north), row increases southward
  const rowF = (bounds.maxLat - lat) / grid.latStep;
  const colF = (lng - bounds.minLng) / grid.lngStep;

  // Out of bounds
  if (rowF < -0.5 || rowF > rows - 0.5 || colF < -0.5 || colF > cols - 0.5) {
    return null;
  }

  // Bilinear interpolation: find surrounding 4 cells
  const r0 = Math.floor(rowF);
  const c0 = Math.floor(colF);
  const r1 = Math.min(r0 + 1, rows - 1);
  const c1 = Math.min(c0 + 1, cols - 1);
  const rr0 = Math.max(r0, 0);
  const cc0 = Math.max(c0, 0);

  const s00 = scores[rr0]?.[cc0];
  const s01 = scores[rr0]?.[c1];
  const s10 = scores[r1]?.[cc0];
  const s11 = scores[r1]?.[c1];

  // If all four corners are null, no data here
  const vals = [s00, s01, s10, s11].filter((v): v is number => v !== null);
  if (vals.length === 0) return null;

  // If some corners are null, use nearest-available average
  if (vals.length < 4) {
    return vals.reduce((a, b) => a + b, 0) / vals.length;
  }

  // Full bilinear interpolation
  const tr = rowF - r0; // fractional row position [0,1]
  const tc = colF - c0; // fractional col position [0,1]
  const top = s00! * (1 - tc) + s01! * tc;
  const bot = s10! * (1 - tc) + s11! * tc;
  return top * (1 - tr) + bot * tr;
}

// ── L.GridLayer factory ─────────────────────────────────────────

function createHeatmapGridLayer(grid: GridData) {
  const HeatmapGrid = L.GridLayer.extend({
    createTile(coords: L.Coords) {
      const tile = document.createElement("canvas");
      tile.width = TILE_SIZE;
      tile.height = TILE_SIZE;

      const ctx = tile.getContext("2d");
      if (!ctx) return tile;

      const map = this._map as L.Map;
      const tileSize = this.getTileSize();
      const tileOriginPx = coords.scaleBy(tileSize);

      // Tile geographic bounds
      const nw = map.unproject(tileOriginPx, coords.z);
      const se = map.unproject(
        L.point(tileOriginPx.x + tileSize.x, tileOriginPx.y + tileSize.y),
        coords.z,
      );

      // Quick check: does this tile overlap the grid bounds at all?
      if (
        nw.lat < grid.bounds.minLat ||
        se.lat > grid.bounds.maxLat ||
        se.lng < grid.bounds.minLng ||
        nw.lng > grid.bounds.maxLng
      ) {
        return tile; // No overlap → transparent
      }

      // Render at reduced resolution for performance
      const sw = Math.ceil(TILE_SIZE / PIXEL_STEP);
      const sh = Math.ceil(TILE_SIZE / PIXEL_STEP);
      const imgData = ctx.createImageData(sw, sh);
      const pixels = imgData.data;

      let hasAnyPixel = false;

      for (let sy = 0; sy < sh; sy++) {
        const py = sy * PIXEL_STEP + PIXEL_STEP / 2;
        for (let sx = 0; sx < sw; sx++) {
          const px = sx * PIXEL_STEP + PIXEL_STEP / 2;

          // Convert tile pixel → lat/lng
          const globalPx = L.point(tileOriginPx.x + px, tileOriginPx.y + py);
          const latlng = map.unproject(globalPx, coords.z);

          // Sample the pre-computed grid with bilinear interpolation
          const score = sampleGrid(grid, latlng.lat, latlng.lng);
          if (score === null) continue;

          hasAnyPixel = true;
          const [r, g, b] = scoreToRgb(score);
          const idx = (sy * sw + sx) * 4;
          pixels[idx] = r;
          pixels[idx + 1] = g;
          pixels[idx + 2] = b;
          pixels[idx + 3] = Math.round(OPACITY * 255);
        }
      }

      if (!hasAnyPixel) return tile;

      // Upscale the low-res render to full tile size
      const offscreen = new OffscreenCanvas(sw, sh);
      const offCtx = offscreen.getContext("2d");
      if (offCtx) {
        offCtx.putImageData(imgData, 0, 0);
        ctx.imageSmoothingEnabled = true;
        ctx.imageSmoothingQuality = "high";
        ctx.drawImage(offscreen, 0, 0, TILE_SIZE, TILE_SIZE);
      }

      return tile;
    },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return new (HeatmapGrid as any)({
    tileSize: TILE_SIZE,
    opacity: 1,
    updateWhenZooming: false,
    keepBuffer: 2,
  }) as L.GridLayer;
}

// ── In-memory cache for fetched grids ───────────────────────────

const gridCache = new Map<string, GridData>();

async function fetchGrid(dimension: ScoreDimension): Promise<GridData | null> {
  const fileName = gridFileFor(dimension);
  if (gridCache.has(fileName)) return gridCache.get(fileName)!;

  try {
    const res = await fetch(`/heatmap/${fileName}.json`);
    if (!res.ok) return null;
    const data: GridData = await res.json();
    gridCache.set(fileName, data);
    return data;
  } catch {
    console.warn(`[HeatmapLayer] Failed to load /heatmap/${fileName}.json`);
    return null;
  }
}

// ── React component ─────────────────────────────────────────────

export default function HeatmapLayer({ dimension }: HeatmapLayerProps) {
  const map = useMap();
  const layerRef = useRef<L.GridLayer | null>(null);
  const [grid, setGrid] = useState<GridData | null>(null);

  // Fetch grid data when dimension changes
  useEffect(() => {
    let cancelled = false;
    fetchGrid(dimension).then((data) => {
      if (!cancelled) setGrid(data);
    });
    return () => { cancelled = true; };
  }, [dimension]);

  // Render layer when grid data is available
  useEffect(() => {
    // Remove old layer
    if (layerRef.current) {
      map.removeLayer(layerRef.current);
      layerRef.current = null;
    }

    if (!grid) return;

    const layer = createHeatmapGridLayer(grid);
    layer.addTo(map);
    layerRef.current = layer;

    return () => {
      if (layerRef.current) {
        map.removeLayer(layerRef.current);
        layerRef.current = null;
      }
    };
  }, [map, grid]);

  return null;
}
