/**
 * HeatmapLayer — pre-computed grid-based heatmap for Leaflet.
 *
 * Fetches a pre-computed score grid from /heatmap/{dimension}.json
 * (generated by scripts/generate_heatmap.py) and renders it using
 * Leaflet's L.GridLayer tile system with bilinear interpolation
 * for smooth color transitions between grid cells.
 *
 * Each grid JSON contains scores at ~400m resolution covering all
 * of NYC. The data is real (computed from actual crime, noise, transit,
 * park, greenery, and convenience datasets) — not interpolated from
 * listing locations.
 *
 * Color scale: green (≥75) → yellow (≥50) → orange (≥25) → red (<25).
 *
 * "Relative to view" mode (store.heatmapRelative): the ramp is
 * renormalized to the p5–p95 score range of the cells currently in
 * view, so locally-flat areas regain contrast. Recomputed on
 * moveend/zoomend (debounced). Null cells stay uncolored either way.
 */

"use client";

import { useEffect, useRef, useState } from "react";
import { useMap } from "react-leaflet";
import type { ScoreDimension } from "@/lib/types";
import { useStore } from "@/lib/store";
import L from "leaflet";

interface HeatmapLayerProps {
  dimension: ScoreDimension;
}

// ── Grid data shape (matches JSON from generate_heatmap.py) ─────

interface GridData {
  bounds: { minLat: number; maxLat: number; minLng: number; maxLng: number };
  rows: number;
  cols: number;
  latStep: number;
  lngStep: number;
  scores: (number | null)[][];
}

// ── Map overlay key → JSON filename ─────────────────────────────

const GRID_FILE: Partial<Record<ScoreDimension, string>> = {
  parks: "green_space", // blended parks + greenery
};

function gridFileFor(dimension: ScoreDimension): string {
  return GRID_FILE[dimension] ?? dimension;
}

// ── Color helpers ───────────────────────────────────────────────

type RGB = [number, number, number];

function lerpColor(a: RGB, b: RGB, t: number): RGB {
  return [
    Math.round(a[0] + (b[0] - a[0]) * t),
    Math.round(a[1] + (b[1] - a[1]) * t),
    Math.round(a[2] + (b[2] - a[2]) * t),
  ];
}

const RED: RGB = [239, 68, 68];
const ORANGE: RGB = [249, 115, 22];
const YELLOW: RGB = [234, 179, 8];
const GREEN: RGB = [34, 197, 94];

// Ramp designed for PERCENTILE data (uniform by construction — exactly
// 10% of residential cells per decile). The old ramp painted the entire
// bottom quartile flat red and reached full green only at ~100, so a
// statistically uniform map READ as "everything at the extremes". This
// ramp gives the middle of the distribution a wide, honest neutral band
// (35–65 ≈ "average is average") and saturates only in the true tails —
// red/green on the map now mean bottom/top ~decile, not bottom/top third.
const NEUTRAL: RGB = [232, 226, 200]; // warm parchment — visibly "no signal"

function scoreToRgb(score: number): RGB {
  const s = Math.max(0, Math.min(100, score));
  if (s >= 90) return GREEN;
  if (s >= 65) return lerpColor(NEUTRAL, GREEN, (s - 65) / 25);
  if (s >= 35) return NEUTRAL; // wide flat middle band
  if (s >= 20) return lerpColor(ORANGE, NEUTRAL, (s - 20) / 15);
  if (s >= 10) return lerpColor(RED, ORANGE, (s - 10) / 10);
  return RED;
}

// Alpha encodes signal strength: the neutral middle whispers (the map
// stops shouting about average blocks) while the distribution tails
// punch through — a red or green area is now ALWAYS a genuine outlier.
function scoreToAlpha(score: number): number {
  const s = Math.max(0, Math.min(100, score));
  const t = Math.min(1, Math.abs(s - 50) / 40); // 0 at median → 1 at |Δ|≥40
  return 0.30 + 0.38 * t * t; // 0.30 mid → 0.68 tails (quadratic ease)
}

// ── Relative-to-view normalization ──────────────────────────────

interface NormRange {
  lo: number;
  hi: number;
}

const RELATIVE_DEBOUNCE_MS = 250;

/**
 * Collect non-null grid values inside the current map bounds and
 * return their p5–p95 range (robust to outliers). Returns null when
 * there is too little data or spread to stretch meaningfully — the
 * caller then falls back to absolute citywide colors.
 */
function computeViewRange(
  grid: GridData,
  bounds: L.LatLngBounds,
): NormRange | null {
  const { bounds: gb, rows, cols, scores } = grid;
  const south = bounds.getSouth();
  const north = bounds.getNorth();
  const west = bounds.getWest();
  const east = bounds.getEast();

  // Grid node r,c sits at (maxLat - r*latStep, minLng + c*lngStep)
  // — same convention as sampleGrid. Restrict the scan to the
  // row/col window overlapping the view.
  const rMin = Math.max(0, Math.floor((gb.maxLat - north) / grid.latStep));
  const rMax = Math.min(rows - 1, Math.ceil((gb.maxLat - south) / grid.latStep));
  const cMin = Math.max(0, Math.floor((west - gb.minLng) / grid.lngStep));
  const cMax = Math.min(cols - 1, Math.ceil((east - gb.minLng) / grid.lngStep));

  const vals: number[] = [];
  for (let r = rMin; r <= rMax; r++) {
    const row = scores[r];
    if (!row) continue;
    for (let c = cMin; c <= cMax; c++) {
      const v = row[c];
      if (v !== null && v !== undefined) vals.push(v);
    }
  }

  if (vals.length < 4) return null;

  vals.sort((a, b) => a - b);
  const lo = vals[Math.floor(0.05 * (vals.length - 1))];
  const hi = vals[Math.ceil(0.95 * (vals.length - 1))];
  if (hi - lo < 1e-6) return null; // Uniform view — nothing to stretch

  return { lo, hi };
}

// ── Tile rendering constants ────────────────────────────────────

const TILE_SIZE = 256;
const PIXEL_STEP = 4; // Render every Nth pixel then upscale for perf
const OPACITY = 0.50;

// ── Bilinear interpolation on the grid ──────────────────────────

function sampleGrid(grid: GridData, lat: number, lng: number): number | null {
  const { bounds, rows, cols, scores } = grid;

  // Convert lat/lng to continuous grid coordinates
  // Row 0 = maxLat (north), row increases southward
  const rowF = (bounds.maxLat - lat) / grid.latStep;
  const colF = (lng - bounds.minLng) / grid.lngStep;

  // Out of bounds
  if (rowF < -0.5 || rowF > rows - 0.5 || colF < -0.5 || colF > cols - 0.5) {
    return null;
  }

  // Bilinear interpolation: find surrounding 4 cells
  const r0 = Math.floor(rowF);
  const c0 = Math.floor(colF);
  const r1 = Math.min(r0 + 1, rows - 1);
  const c1 = Math.min(c0 + 1, cols - 1);
  const rr0 = Math.max(r0, 0);
  const cc0 = Math.max(c0, 0);

  const s00 = scores[rr0]?.[cc0];
  const s01 = scores[rr0]?.[c1];
  const s10 = scores[r1]?.[cc0];
  const s11 = scores[r1]?.[c1];

  // If all four corners are null, no data here
  const vals = [s00, s01, s10, s11].filter((v): v is number => v !== null);
  if (vals.length === 0) return null;

  // If some corners are null, use nearest-available average
  if (vals.length < 4) {
    return vals.reduce((a, b) => a + b, 0) / vals.length;
  }

  // Full bilinear interpolation
  const tr = rowF - r0; // fractional row position [0,1]
  const tc = colF - c0; // fractional col position [0,1]
  const top = s00! * (1 - tc) + s01! * tc;
  const bot = s10! * (1 - tc) + s11! * tc;
  return top * (1 - tr) + bot * tr;
}

// ── L.GridLayer factory ─────────────────────────────────────────

function createHeatmapGridLayer(
  grid: GridData,
  normRef: { current: NormRange | null },
) {
  const HeatmapGrid = L.GridLayer.extend({
    createTile(coords: L.Coords) {
      const tile = document.createElement("canvas");
      tile.width = TILE_SIZE;
      tile.height = TILE_SIZE;

      const ctx = tile.getContext("2d");
      if (!ctx) return tile;

      const map = this._map as L.Map;
      const tileSize = this.getTileSize();
      const tileOriginPx = coords.scaleBy(tileSize);

      // Tile geographic bounds
      const nw = map.unproject(tileOriginPx, coords.z);
      const se = map.unproject(
        L.point(tileOriginPx.x + tileSize.x, tileOriginPx.y + tileSize.y),
        coords.z,
      );

      // Quick check: does this tile overlap the grid bounds at all?
      if (
        nw.lat < grid.bounds.minLat ||
        se.lat > grid.bounds.maxLat ||
        se.lng < grid.bounds.minLng ||
        nw.lng > grid.bounds.maxLng
      ) {
        return tile; // No overlap → transparent
      }

      // Render at reduced resolution for performance
      const sw = Math.ceil(TILE_SIZE / PIXEL_STEP);
      const sh = Math.ceil(TILE_SIZE / PIXEL_STEP);
      const imgData = ctx.createImageData(sw, sh);
      const pixels = imgData.data;

      let hasAnyPixel = false;

      // Relative-to-view: stretch [lo, hi] onto the full 0–100 ramp.
      // Read once per tile; layer.redraw() re-renders when it changes.
      const norm = normRef.current;

      for (let sy = 0; sy < sh; sy++) {
        const py = sy * PIXEL_STEP + PIXEL_STEP / 2;
        for (let sx = 0; sx < sw; sx++) {
          const px = sx * PIXEL_STEP + PIXEL_STEP / 2;

          // Convert tile pixel → lat/lng
          const globalPx = L.point(tileOriginPx.x + px, tileOriginPx.y + py);
          const latlng = map.unproject(globalPx, coords.z);

          // Sample the pre-computed grid with bilinear interpolation
          const score = sampleGrid(grid, latlng.lat, latlng.lng);
          if (score === null) continue; // Null cells stay uncolored in both modes

          hasAnyPixel = true;
          const display = norm
            ? ((score - norm.lo) / (norm.hi - norm.lo)) * 100
            : score;
          const [r, g, b] = scoreToRgb(display); // scoreToRgb clamps to [0,100]
          const idx = (sy * sw + sx) * 4;
          pixels[idx] = r;
          pixels[idx + 1] = g;
          pixels[idx + 2] = b;
          pixels[idx + 3] = Math.round(scoreToAlpha(display) * 255);
        }
      }

      if (!hasAnyPixel) return tile;

      // Upscale the low-res render to full tile size
      const offscreen = new OffscreenCanvas(sw, sh);
      const offCtx = offscreen.getContext("2d");
      if (offCtx) {
        offCtx.putImageData(imgData, 0, 0);
        ctx.imageSmoothingEnabled = true;
        ctx.imageSmoothingQuality = "high";
        ctx.drawImage(offscreen, 0, 0, TILE_SIZE, TILE_SIZE);
      }

      return tile;
    },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return new (HeatmapGrid as any)({
    tileSize: TILE_SIZE,
    opacity: 1,
    updateWhenZooming: false,
    keepBuffer: 2,
  }) as L.GridLayer;
}

// ── In-memory cache for fetched grids ───────────────────────────

const gridCache = new Map<string, GridData>();

async function fetchGrid(dimension: ScoreDimension): Promise<GridData | null> {
  const fileName = gridFileFor(dimension);
  if (gridCache.has(fileName)) return gridCache.get(fileName)!;

  try {
    const res = await fetch(`/heatmap/${fileName}.json`, { cache: "no-store" });
    if (!res.ok) return null;
    const data: GridData = await res.json();
    gridCache.set(fileName, data);
    return data;
  } catch {
    console.warn(`[HeatmapLayer] Failed to load /heatmap/${fileName}.json`);
    return null;
  }
}

// ── React component ─────────────────────────────────────────────

export default function HeatmapLayer({ dimension }: HeatmapLayerProps) {
  const map = useMap();
  const relative = useStore((s) => s.heatmapRelative);
  const layerRef = useRef<L.GridLayer | null>(null);
  const normRef = useRef<NormRange | null>(null);
  const [grid, setGrid] = useState<GridData | null>(null);

  // Fetch grid data when dimension changes
  useEffect(() => {
    let cancelled = false;
    fetchGrid(dimension).then((data) => {
      if (!cancelled) setGrid(data);
    });
    return () => { cancelled = true; };
  }, [dimension]);

  // Render layer when grid data is available
  useEffect(() => {
    // Remove old layer
    if (layerRef.current) {
      map.removeLayer(layerRef.current);
      layerRef.current = null;
    }

    if (!grid) return;

    const layer = createHeatmapGridLayer(grid, normRef);
    layer.addTo(map);
    layerRef.current = layer;

    return () => {
      if (layerRef.current) {
        map.removeLayer(layerRef.current);
        layerRef.current = null;
      }
    };
  }, [map, grid]);

  // Relative-to-view normalization: recompute the visible-score range
  // on toggle and on map moveend/zoomend (debounced), then redraw.
  useEffect(() => {
    if (!grid) return;

    const apply = () => {
      normRef.current = computeViewRange(grid, map.getBounds());
      layerRef.current?.redraw();
    };

    if (!relative) {
      // Back to absolute citywide colors
      if (normRef.current !== null) {
        normRef.current = null;
        layerRef.current?.redraw();
      }
      return;
    }

    apply(); // Immediate on toggle-on / grid load

    let timer: ReturnType<typeof setTimeout> | null = null;
    const debounced = () => {
      if (timer) clearTimeout(timer);
      timer = setTimeout(apply, RELATIVE_DEBOUNCE_MS);
    };
    map.on("moveend zoomend", debounced);

    return () => {
      if (timer) clearTimeout(timer);
      map.off("moveend zoomend", debounced);
    };
  }, [map, grid, relative]);

  return null;
}
